name: Run Python Unittests

on:
  push:
    branches:
      - main
      - "**/task-*"
  pull_request:

jobs:
  unittest:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Choose the Python version needed for your project

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run unittests
    - name: Run Tests
      run: |
        python -m unittest discover tests/
